# Generated by Django 4.2 on 2024-06-02 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appFOOD', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedidos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('hora_pedido', models.TimeField()),
                ('direccion_entrega', models.CharField(max_length=100)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_productos', models.IntegerField()),
                ('precio_producto', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCART.pedido')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appFOOD.producto')),
            ],
            options={
                'verbose_name': 'Detallepedido',
                'verbose_name_plural': 'Detallepedidos',
                'db_table': 'detalle_pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('comprado', models.BooleanField(default=False)),
                ('id_pedido', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='appCART.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFOOD.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carrito',
            },
        ),
    ]
