# Generated by Django 4.2 on 2024-06-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCART', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='hora_pedido',
            field=models.TimeField(null=True),
        ),
    ]
