# Generated by Django 4.2 on 2024-06-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCART', '0002_alter_pedido_direccion_entrega_alter_pedido_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='cantidad_productos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.FloatField(null=True),
        ),
    ]
