# Generated by Django 4.2 on 2024-06-02 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCART', '0003_alter_detallepedido_cantidad_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='detalles', to='appCART.pedido'),
        ),
    ]
