# Generated by Django 4.2 on 2024-06-02 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFOOD', '0002_alter_producto_descripcion'),
        ('appCART', '0004_alter_detallepedido_id_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCART.pedido'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito_producto', to='appFOOD.producto'),
        ),
    ]
