# Generated by Django 4.2 on 2024-06-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFOOD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
